version: '3'
services:

  frontend:
    build: .
    #command: nodemon --watch /code -e js,jsx,html
    container_name: weatherapp_frontend
    ports:
      - '8000:8000'
    volumes:
      - /Applications/MAMP/htdocs/weatherapp/frontend:/code
    environment:
      NODE_ENV: development

  backend:
    build: ./backend
    #command: nodemon --watch /code -e js,jsx,html
    container_name: weatherapp_backend
    ports:
      - '9000:9000'
    environment:
      NODE_ENV: development
